name: Update Stats

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update README with latest stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
