name: Update Stats on README
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Dieman's README stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LOC_CHART: "False"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_TIMEZONE: "True"
          SHOW_OS: "True"
          SHOW_EDITORS: "True"
          SHOW_LINES_OF_CODE: "True"
