name: Waka Readme
on:
  schedule:
    # Runs at 12am IST
    - cron: "0 */2 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Dieman's README stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_COMMIT: "True"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "False"
